Update after-release.yml

diff --git a/.github/workflows/after-release.yml b/.github/workflows/after-release.yml
--- a/.github/workflows/after-release.yml
+++ b/.github/workflows/after-release.yml
@@ -52,8 +52,8 @@ jobs:
         git push -u origin $NEW_BRANCH --force
     - name: Create Pull Request
       run: |
-        if ! bash -c "$GH_PR_COMMAND"; then
-          echo "::warning:: The creation of Pull Request failed. Your project or organization may not allow to create PR in Actions
-          Run the following command locally
-          $GH_PR_COMMAND"
+        if ! output=$(bash -c "$GH_PR_COMMAND"); then
+          echo "::warning:: $output"
+          echo "::warning:: The creation of Pull Request failed. Your project or organization may not allow to create PR in Actions. Run the following command locally"
+          echo "::warning:: $GH_PR_COMMAND"
         fi
